#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace YuzeToolkit.UnityAgent
{
    internal sealed class AgentContentBuildProcessor : BuildPlayerProcessor, IPostprocessBuildWithReport
    {
        private const string GeneratedFolderName = "UnityAgentToolBuildContent";
        private const string ContentFolderName = "UnityAgentContent";
        private const string ContentRelativePath = AgentPaths.SettingsDirectoryName + "/" + ContentFolderName;
        private const string MarkerFileName = ".unityagent-generated";
        private const long MaximumFileBytes = 8L * 1024L * 1024L;
        private const long MaximumTotalBytes = 64L * 1024L * 1024L;
        private const int MaximumFileCount = 4096;

        public override int callbackOrder => 1000;

        public override void PrepareForBuild(BuildPlayerContext buildPlayerContext)
        {
            if (buildPlayerContext == null) throw new ArgumentNullException(nameof(buildPlayerContext));
            var contentPath = PrepareGeneratedContent();
            buildPlayerContext.AddAdditionalPathToStreamingAssets(contentPath, ContentRelativePath);
        }

        public void OnPostprocessBuild(BuildReport report)
        {
            CleanupGeneratedContent();
        }

        private static string PrepareGeneratedContent()
        {
            CleanupGeneratedContent();
            var projectRoot = GetProjectRoot();
            var reservedStreamingAssetsPath = Path.Combine(
                projectRoot, "Assets", "StreamingAssets", AgentPaths.SettingsDirectoryName, ContentFolderName);
            if (Directory.Exists(reservedStreamingAssetsPath) || File.Exists(reservedStreamingAssetsPath))
                throw new BuildFailedException(
                    $"UnityAgentTool reserves StreamingAssets/{ContentRelativePath}; remove or rename the existing path: " +
                    reservedStreamingAssetsPath);
            var stageRoot = GetStageRoot(projectRoot);
            if (Directory.Exists(stageRoot))
                throw new BuildFailedException(
                    $"UnityAgentTool build staging path already exists and is not owned by UnityAgentTool: {stageRoot}");

            Directory.CreateDirectory(stageRoot);
            File.WriteAllText(Path.Combine(stageRoot, MarkerFileName),
                "Generated by UnityAgentTool build processor.");
            try
            {
                var contentTarget = Path.Combine(stageRoot, AgentPaths.SettingsDirectoryName, ContentFolderName);
                Directory.CreateDirectory(contentTarget);
                UnityAgentHost.Default.EnsureInitializedAsync().GetAwaiter().GetResult();
                var settings = UnityAgentHost.Default.Settings;
                var agentsManifest = new List<object?>();
                var skillsManifest = new List<object?>();
                long copiedBytes = 0;
                var copiedFiles = 0;

                PackageAgentsRoots(settings.AgentsRoots, projectRoot, contentTarget, agentsManifest,
                    ref copiedBytes, ref copiedFiles);
                PackageSkillRoots(settings.SkillRoots, contentTarget, skillsManifest,
                    ref copiedBytes, ref copiedFiles);

                File.WriteAllText(Path.Combine(contentTarget, "manifest.json"), LitJson.Stringify(EvalData.Obj(
                    ("schemaVersion", 2),
                    ("generatedAtUtc", DateTime.UtcNow.ToString("O")),
                    ("agentsRoots", agentsManifest),
                    ("skillRoots", skillsManifest))));
                return contentTarget;
            }
            catch
            {
                CleanupGeneratedContent();
                throw;
            }
        }

        private static void PackageAgentsRoots(
            IReadOnlyList<AgentPathLocation> locations,
            string projectRoot,
            string contentTarget,
            List<object?> manifest,
            ref long copiedBytes,
            ref int copiedFiles)
        {
            ValidateRootIds(locations, "AGENTS.md");
            var seenFiles = new HashSet<string>(PathComparer);
            var outputIndex = 0;
            for (var rootIndex = 0; rootIndex < locations.Count; rootIndex++)
            {
                var location = locations[rootIndex];
                if (!location.EmbedInPlayerBuild) continue;
                var sourceRoot = ResolveBuildLocation(location, "AGENTS.md", isSkillRoot: false);
                if (sourceRoot == null) continue;
                foreach (var sourceFile in FindAgentsFiles(sourceRoot, projectRoot))
                {
                    var fullSource = Path.GetFullPath(sourceFile);
                    if (!seenFiles.Add(fullSource)) continue;
                    var relativeDestination = $"agents/{outputIndex:D4}";
                    var destinationRoot = Path.Combine(contentTarget,
                        relativeDestination.Replace('/', Path.DirectorySeparatorChar));
                    Directory.CreateDirectory(destinationRoot);
                    CopyFile(new FileInfo(fullSource), Path.Combine(destinationRoot, "AGENTS.md"),
                        ref copiedBytes, ref copiedFiles);
                    manifest.Add(EvalData.Obj(
                        ("id", $"agents-{outputIndex:D4}"),
                        ("path", relativeDestination)));
                    outputIndex++;
                }
            }
        }

        private static void PackageSkillRoots(
            IReadOnlyList<AgentPathLocation> locations,
            string contentTarget,
            List<object?> manifest,
            ref long copiedBytes,
            ref int copiedFiles)
        {
            ValidateRootIds(locations, "Skill");
            var seenRoots = new HashSet<string>(PathComparer);
            var outputIndex = 0;
            foreach (var location in locations)
            {
                if (!location.EmbedInPlayerBuild) continue;
                var sourceRoot = ResolveBuildLocation(location, "Skill", isSkillRoot: true);
                if (sourceRoot == null) continue;
                if (!seenRoots.Add(sourceRoot)) continue;
                var relativeDestination = $"skills/{outputIndex:D4}";
                var destinationRoot = Path.Combine(contentTarget,
                    relativeDestination.Replace('/', Path.DirectorySeparatorChar));
                CopyDirectory(sourceRoot, destinationRoot, ref copiedBytes, ref copiedFiles);
                manifest.Add(EvalData.Obj(
                    ("id", location.Id),
                    ("path", relativeDestination)));
                outputIndex++;
            }
        }

        private static string? ResolveBuildLocation(
            AgentPathLocation location,
            string kind,
            bool isSkillRoot)
        {
            try
            {
                AgentPaths.Validate(location);
                var fullPath = isSkillRoot ? AgentPaths.ResolveSkill(location) : AgentPaths.Resolve(location);
                if (!Directory.Exists(fullPath))
                {
                    LogSys.LogWarning(
                        $"UnityAgentTool skipped embedded {kind} root '{location.Id}' because the source " +
                        $"directory does not exist: {fullPath}");
                    return null;
                }
                RejectReparsePoint(new DirectoryInfo(fullPath));
                return fullPath;
            }
            catch (BuildFailedException)
            {
                throw;
            }
            catch (Exception exception)
            {
                throw new BuildFailedException(
                    $"UnityAgentTool {kind} root '{location?.Id}' is invalid: {exception.Message}");
            }
        }

        private static void ValidateRootIds(IReadOnlyList<AgentPathLocation> locations, string kind)
        {
            if (locations == null) throw new BuildFailedException($"UnityAgentTool {kind} roots collection is null.");
            var ids = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            foreach (var location in locations)
            {
                if (location == null)
                    throw new BuildFailedException($"UnityAgentTool {kind} roots contain a null entry.");
                if (!ids.Add(location.Id))
                    throw new BuildFailedException(
                        $"UnityAgentTool {kind} root id '{location.Id}' is configured more than once.");
            }
        }

        private static IEnumerable<string> FindAgentsFiles(string rootPath, string workingDirectory)
        {
            var root = Path.GetFullPath(rootPath);
            RejectReparsePoint(new DirectoryInfo(root));
            var result = new List<string>();
            AddAgentsFile(Path.Combine(root, "AGENTS.md"), result);
            var working = Path.GetFullPath(workingDirectory);
            if (!AgentPaths.IsSameOrDescendant(working, root)) return result;
            var relative = AgentPaths.PathsEqual(working, root)
                ? string.Empty
                : working.Substring(EnsureTrailingSeparator(root).Length);
            var current = root;
            foreach (var segment in relative.Split(
                         new[] { Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar },
                         StringSplitOptions.RemoveEmptyEntries))
            {
                current = Path.Combine(current, segment);
                RejectReparsePoint(new DirectoryInfo(current));
                AddAgentsFile(Path.Combine(current, "AGENTS.md"), result);
            }
            return result;
        }

        private static void AddAgentsFile(string path, ICollection<string> result)
        {
            if (!File.Exists(path)) return;
            RejectReparsePoint(new FileInfo(path));
            result.Add(path);
        }

        private static void CopyDirectory(
            string source,
            string destination,
            ref long copiedBytes,
            ref int copiedFiles)
        {
            var sourceInfo = new DirectoryInfo(source);
            RejectReparsePoint(sourceInfo);
            Directory.CreateDirectory(destination);
            foreach (var file in sourceInfo.GetFiles().OrderBy(file => file.Name, StringComparer.Ordinal))
            {
                if (file.Extension.Equals(".meta", StringComparison.OrdinalIgnoreCase) ||
                    file.Name.Equals(".DS_Store", StringComparison.Ordinal))
                    continue;
                CopyFile(file, Path.Combine(destination, file.Name), ref copiedBytes, ref copiedFiles);
            }
            foreach (var directory in sourceInfo.GetDirectories().OrderBy(directory => directory.Name,
                         StringComparer.Ordinal))
                CopyDirectory(directory.FullName, Path.Combine(destination, directory.Name),
                    ref copiedBytes, ref copiedFiles);
        }

        private static void CopyFile(
            FileInfo file,
            string destination,
            ref long copiedBytes,
            ref int copiedFiles)
        {
            RejectReparsePoint(file);
            if (file.Length > MaximumFileBytes)
                throw new BuildFailedException(
                    $"UnityAgentTool content file exceeds the {MaximumFileBytes / 1024 / 1024} MB limit: {file.FullName}");
            if (copiedFiles >= MaximumFileCount)
                throw new BuildFailedException(
                    $"UnityAgentTool content exceeds the {MaximumFileCount} file limit.");
            if (copiedBytes + file.Length > MaximumTotalBytes)
                throw new BuildFailedException(
                    $"UnityAgentTool content exceeds the {MaximumTotalBytes / 1024 / 1024} MB total limit.");
            file.CopyTo(destination, true);
            copiedFiles++;
            copiedBytes += file.Length;
        }

        private static void RejectReparsePoint(FileSystemInfo info)
        {
            if ((info.Attributes & FileAttributes.ReparsePoint) != 0)
                throw new BuildFailedException(
                    $"UnityAgentTool does not package symlinked content: {info.FullName}");
        }

        private static void CleanupGeneratedContent()
        {
            var stageRoot = GetStageRoot(GetProjectRoot());
            if (!Directory.Exists(stageRoot)) return;
            if (!File.Exists(Path.Combine(stageRoot, MarkerFileName))) return;
            Directory.Delete(stageRoot, true);
        }

        private static string GetProjectRoot()
        {
            return Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
        }

        private static string GetStageRoot(string projectRoot)
        {
            return Path.Combine(projectRoot, "Temp", GeneratedFolderName);
        }

        private static string EnsureTrailingSeparator(string path)
        {
            if (path.Length > 0 &&
                (path[path.Length - 1] == Path.DirectorySeparatorChar ||
                 path[path.Length - 1] == Path.AltDirectorySeparatorChar)) return path;
            return path + Path.DirectorySeparatorChar;
        }

        private static StringComparer PathComparer =>
            Application.platform == RuntimePlatform.WindowsEditor
                ? StringComparer.OrdinalIgnoreCase
                : StringComparer.Ordinal;
    }
}
